
export const CHANGE_OPTION = 'CHANGE_OPTION';
export const CHANGE_OPTIONS = 'CHANGE_OPTIONS';
export const CHANGE_WORDS_PER_DAY_OPTION = 'CHANGE_WORDS_PER_DAY_OPTION';

export const SAVE_STATISTIC = 'SAVE_STATISTIC';
export const LOAD_STATISTIC = 'LOAD_STATISTIC';
export const DELETE_STATISTIC = 'DELETE_STATISTIC';